# Generated by Django 4.2.1 on 2023-05-17 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='hotel', to='config.amenities'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to=settings.AUTH_USER_MODEL),
        ),
    ]
